POST https://api.anthropic.com/v1/messages
x-api-key: {{ANTHROPIC_API_KEY}}
anthropic-version: 2023-06-01
content-type: application/json

{
  "model": "claude-3-haiku-20240307",
  "max_tokens": 1000,
  "messages": [
    {
      "role": "user",
      "content": "당신은 이제부터 Computer Science에 대해 질문하는 면접관이다. 당신이 안내한 질문에 대해 내가 답변을 하면, 그에 대한 점수를 그동안 해왔던 답변도 포함하여 10점 단위로 평가 및 이유와 공부할 수 있는 키워드, 꼬리 질문을 제시해주길 바란다. 점수에 대한 기준은 다음과 같다. (0: 기초 부족, 10~30: 기초 수준만 아는 상태, 40~60: 어느 정도 알고 있음, 70~90: 어느 정도 깊게 알고 있음, 100: 매우 깊게 알고 있음) 답변 형식은 다음과 같다. (매우 중요: 어떠한 답변을 해도 아래 형식을 반드시 맞출 것. 점수와 꼬리 질문은 정규식으로 추출하기 때문에 형식을 맞추지 않으면 정상적으로 추출되지 않을 수 있다.) 답변에 대한 점수: nn점 이유: ~~에 대한 설명은 부족합니다 / ~~에 대한 설명은 틀렸습니다 / ~~에 대해 더 깊게 공부하세요. 공부할 수 있는 키워드: ~~ / ~~ / ~~ 꼬리 질문: ~~에 대해 더 깊게 설명해보세요. 답변에 대한 점수 / 이유 / 공부할 수 있는 키워드 / 꼬리 질문 항목에 대해 줄바꿈하여 작성해주길 바람."
    },
    {
      "role": "assistant",
      "content": "네, 알겠습니다. 제공해주신 형식에 맞추어 답변드리겠습니다. 제가 면접관으로 질문드릴 내용은 다음과 같습니다. OSI 7계층에 대해 설명해보세요."
    },
    {
      "role": "user",
      "content": "OSI 7계층은 네트워크를 구성하는 여러 역할들을 레이어를 통해 구분한 것입니다. 물리/데이터 링크/네트워크/전송/세션/표현/응용 계층으로 구성되어 있고 각 계층마다 각자의 프로토콜을 이용해 역할을 수행합니다. 각 계층은 하위 계층에 의존하는 형태로 구성되어 있습니다. 예를 들어 7계층인 HTTP 프로토콜은 4계층인 TCP 프로토콜에 의존합니다."
    }
  ]
}
