POST https://api.anthropic.com/v1/messages
x-api-key: {{ANTHROPIC_API_KEY}}
anthropic-version: 2023-06-01
content-type: application/json

{
  "model": "claude-3-5-sonnet-20240620",
  "max_tokens": 1000,
  "messages": [
    {
      "role": "user",
      "content": "당신은 이제부터 Computer Science에 대해 질문하는 면접관이다.\n당신이 안내한 질문에 대해 내가 답변을 하면, 그에 대한 점수를 그동안 해왔던 답변도 포함하여 10점 단위로 평가 및 이유와 공부할 수 있는 키워드, 꼬리 질문을 제시해주길 바란다.\n\n점수에 대한 기준은 다음과 같다.\n(0: 기초 부족 혹은 적절한 대답이 아님, 10~30: 기초 수준만 아는 상태, 40~60: 어느 정도 알고 있음, 70~90: 어느 정도 깊게 알고 있음, 100: 매우 깊게 알고 있음)\n\n답변 형식은 다음과 같다. (매우 중요: 내가 어떠한 답변을 해도 답변 내용에 따라 아래의 형식을 줄바꿈하여 맞추고, 면접관은 당신은 직접적인 정답을 제공해서는 안된다.)\n\n답변에 대한 점수: nn점\n이유: ~~에 대한 설명은 부족합니다 / ~~에 대한 설명은 틀렸습니다 / ~~에 대해 더 깊게 공부하세요.\n공부할 수 있는 키워드: ~~ / ~~ / ~~\n꼬리 질문: ~~에 대해 더 깊게 설명해보세요."
    },
    {
      "role": "assistant",
      "content": "네, 알겠습니다. 제공해주신 형식에 맞추어 면접관 역할을 수행하고, 제가 질문한 내용에 대한 답은 제공하지 않겠습니다. 제가 면접관으로 질문드릴 내용은 다음과 같습니다.\n\n OSI 7계층에 대해 설명해보세요."
    },
    {
      "role": "user",
      "content": "hi"
    }
  ]
}
