spring:
  application:
    name: cs-ai-interviewer
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false

---
spring.config.activate.on-profile: local, default

spring:
  datasource:
    name: cs-ai-interviewer
    url: jdbc:h2:mem:cs-ai-interviewer
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    name: cs-ai-interviewer
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    show-sql: false
  flyway:
    enabled: true
