spring:
  application:
    name: cs-ai-interviewer
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false
  flyway:
    enabled: false

claude:
  api-key: ${CLAUDE_API_KEY}

---
spring.config.activate.on-profile: local, default

spring:
  datasource:
    name: cs-ai-interviewer
    url: jdbc:h2:mem:cs-ai-interviewer
    username: sa
    password:
    driver-class-name: org.h2.Driver
  session:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

---
spring.config.activate.on-profile: dev

spring:
  datasource:
    name: cs-ai-interviewer
    url: jdbc:mariadb://localhost:3306/cs-ai
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  session:
    jdbc:
      initialize-schema: never
  flyway:
    enabled: true # NOTE: dev profile is set to enable flyway
  jpa:
    hibernate:
      ddl-auto: validate # NOTE: dev profile is set to `validate`
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    name: cs-ai-interviewer
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  session:
    jdbc:
      initialize-schema: never
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    show-sql: false
