spring:
  application:
    name: cs-ai-interviewer
  config:
    import: classpath:version.properties # NOTE: version.properties 파일은 writeVersion task 실행 시 생성됨
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false
  flyway:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

claude:
  api-key: ${CLAUDE_API_KEY}

jwt:
  secret: "12345678901234567890123456789012345678901234567890123456789012"

---
spring.config.activate.on-profile: local, default, test

spring:
  datasource:
    name: cs-ai-interviewer
    url: jdbc:h2:mem:cs-ai-interviewer
    username: sa
    password:
    driver-class-name: org.h2.Driver
  session:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    dev:
      jxmen:
        cs:
          ai:
            interviewer: DEBUG

---
spring.config.activate.on-profile: dev

spring:
  datasource:
    name: cs-ai-interviewer
    url: jdbc:mariadb://localhost:3313/cs-ai
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  session:
    jdbc:
      initialize-schema: never
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

---
spring.config.activate.on-profile: prod

spring:
  datasource:
    name: cs-ai-interviewer
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  session:
    jdbc:
      initialize-schema: never
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
